# Custom Linear Classifier for Image Classification

Load the custom dataset/well known dataset

In [9]:
import torch
import torch.nn as nn

In [10]:
model = nn.Linear(1,1)

In [11]:
x = torch.tensor([2.0])
model(x)

tensor([-0.2924], grad_fn=<AddBackward0>)

In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2452]], requires_grad=True), Parameter containing:
 tensor([0.1980], requires_grad=True)]

In [13]:
class LinearClassifier(nn.Module):
    def __init__(self,n_in,n_out):
        super().__init__
        self.linear = nn.Linear(n_in,n_out)
    def fit(self,X_data):
        pass
    def predict(self,X):
        pass
    def train(self):
        pass